crtmqm TUTORIAL_QM_LOCAL
strmqm TUTORIAL_QM_LOCAL
runmqsc TUTORIAL_QM_LOCAL < <FILEPATH1>\QUEUEMANAGERLOCAL.mqsc
crtmqm TUTORIAL_QM_REMOTE
strmqm TUTORIAL_QM_REMOTE
runmqsc TUTORIAL_QM_REMOTE < <FILEPATH2>\QUEUEMANAGERREMOTE.mqsc